import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Tables from '../components/first3tables'
import MantineTable from '../components/mantineTabbles'
import styles from '../styles/Home.module.css'


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <MantineTable/>
    <script src='./api/codeForInsertion'></script>
    </div>
  )
}

export default Home
